Add initial macOS support
provenance-io/provenance-mobile-wallet pull request #216
Opened 2022-05-13 18:45 UTC by royd

This branch is built on top of royd/flutter-3.0.0

2022-05-13 21:33 UTC, jakegraves-figure submitted a review, later dismissed

2022-05-16 14:56 UTC, dhancockFigure requested changes
The onboarding screens do not seem to scroll when, they must be resized to hit the next button. 

when screens would been to be adjusted so that they can deal with being resized.

the icons need to be updated so that os x icons are generated

the app crashed while scanning the qr code with "mobile_scanner/MobileScannerPlugin.swift:93: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value"

2022-05-16 15:00 UTC, royd commented
> The onboarding screens do not seem to scroll when, they must be resized to hit the next button.

is this on macOS or a different platform?

2022-05-16 15:04 UTC, royd commented
> when screens would been to be adjusted so that they can deal with being resized.

My thought is that full support for macOS screen resizing would be done in subsequent work

2022-05-16 19:35 UTC, closed without merging