221 manual passphrase entry
provenance-io/provenance-mobile-wallet pull request #222
Opened 2022-05-17 16:13 UTC by jakegraves-figure

Changed gears in the middle of this branch, and started working with the `Autocomplete` widget.

`Autocomplete` was a bit different than what I was expecting, not letting me supply a `TextEditingController` but it gave me access to the one it had, so I made it work with the existing logic.

Testing with iOS and the Android emulator I was running, there didn't seem to be any bug regression.

2022-05-17 17:42 UTC, royd approved these changes

2022-05-17 20:55 UTC, dhancockFigure reviewed
Is there a way to make the suggestion popup stand out a little more? I missed a couple of times

2022-05-17 21:09 UTC, jakegraves-figure commented
> Is there a way to make the suggestion popup stand out a little more? I missed a couple of times

I could probably make the suggestion a shade lighter.

2022-05-17 21:11 UTC, dhancockFigure commented
> 
or even just add a border

2022-05-18 14:42 UTC, dhancockFigure approved these changes
looks good

2022-05-18 14:48 UTC, royd requested changes

2022-05-18 14:48 UTC, royd commented on lib/screens/recover_passphrase_entry_screen/recover_passphrase_bloc.dart
> +    return textControllers.entries.length == 24 &&
Could use `_wordsCount`

2022-05-18 14:48 UTC, royd commented on lib/screens/recover_passphrase_entry_screen/recover_passphrase_entry_screen.dart
> +              children: Iterable<int>.generate(24).toList().map(
For all the `23` and `24` values, I would base them off of `wordCount` from the bloc

2022-05-18 20:28 UTC, royd approved these changes

2022-05-18 20:29 UTC, dhancockFigure approved these changes

2022-05-18 22:29 UTC, merged