added the notification bell
provenance-io/provenance-mobile-wallet pull request #250
Opened 2022-06-21 20:52 UTC by dhancockFigure

Added the notification widget that will be used to indicate a multisig notification. It is enabled when the multiSig notification i enabled.

2022-06-21 21:00 UTC, jakegraves-figure approved these changes

2022-06-21 22:38 UTC, royd requested changes

2022-06-21 22:38 UTC, royd commented on test/common/widgets/notification_bell_test.dart
> +const GOLDEN_ROOT = "../../goldens/common/widgets/notification_bell";
lower camel case by convention

2022-06-22 15:00 UTC, dhancockFigure commented on test/common/widgets/notification_bell_test.dart
> +const GOLDEN_ROOT = "../../goldens/common/widgets/notification_bell";
updated to camel case

2022-06-22 15:09 UTC, royd approved these changes

2022-06-22 15:49 UTC, merged