Jake/deposit design
provenance-io/provenance-mobile-wallet pull request #342
Opened 2022-09-26 16:07 UTC by jakegraves-figure

2022-09-27 16:25 UTC, royd requested changes

2022-09-27 16:25 UTC, royd commented on lib/common/theme.dart
> +  static const Color _depositPeriod = Color(0xFFFEC10B);
These new names are context-specific, whereas the others are generic. Should these new names be generic?

2022-09-27 16:25 UTC, royd commented on lib/util/extensions/string_extensions.dart
> +  String capitalizeAll() {
What about `capitalizeWords`?

2022-09-27 22:24 UTC, royd approved these changes

2022-09-28 18:35 UTC, dhancockFigure approved these changes

2022-10-04 15:14 UTC, merged